(defun swagger-parse ()
  (interactive)
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*string($date-time)$" "\\1var \\2: Date?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*string$" "\\1var \\2: String?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*	integer($int32)*$" "\\1var \\2: Int?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*	integer($int64)*$" "\\1var \\2: Int?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*boolean" "\\1var \\2: Bool?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*\\[...\\]$" "//\\1var \\2: [...]?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*number($float)$" "\\1var \\2: Double?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*number($double)$" "\\1var \\2: Double?"))
  (save-excursion (replace-regexp "^\\([ 	]*\\)\\(\\w+\\)[ 	]*{...}$" "//\\1var \\2: {...}?")))

(provide 'swagger-parse)
