(defadvice previous-line (after recenter-after activate) (recenter))
(defadvice next-line (after recenter-after activate) (recenter))
(defadvice forward-char (after recenter-after activate) (recenter))
(defadvice backward-char (after recenter-after activate) (recenter))
(defadvice left-char (after recenter-after activate) (recenter))
(defadvice right-char (after recenter-after activate) (recenter))
(defadvice isearch-repeat-forward (after isearch-repeat-forward-recenter activate) (recenter))
(defadvice isearch-repeat-backward (after isearch-repeat-backward-recenter activate) (recenter))
